# Generated by Django 5.2.12 on 2026-04-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Defects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('responsible_department', models.CharField()),
                ('responsible_line', models.CharField()),
                ('responsible_station', models.CharField()),
                ('responsible_person', models.CharField()),
                ('countermeasure', models.TextField()),
                ('quality_remark', models.CharField()),
                ('approval_by_quality', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('in_progress', 'В работе'), ('monitoring', 'Мониторинг'), ('closed', 'Закрыт'), ('repeat', 'Повтор')], default='open')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='defects/', verbose_name='Фото')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
