# Generated by Django 5.2.12 on 2026-04-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defects',
            name='approval_by_quality',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='defects',
            name='countermeasure',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='defects',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='defects',
            name='meeting_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='defects',
            name='quality_remark',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='defects',
            name='responsible_department',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='defects',
            name='responsible_line',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='defects',
            name='responsible_person',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='defects',
            name='responsible_station',
            field=models.CharField(blank=True, null=True),
        ),
    ]
