# Generated by Django 5.2.12 on 2026-04-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0002_alter_defects_approval_by_quality_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defects',
            name='photo',
        ),
        migrations.AlterField(
            model_name='defects',
            name='status',
            field=models.CharField(choices=[('in_progress', 'В работе'), ('monitoring', 'Мониторинг'), ('closed', 'Закрыт'), ('repeat', 'Повтор')], default='in_process'),
        ),
    ]
