# Generated by Django 5.2.12 on 2026-04-28 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0003_remove_defects_photo_alter_defects_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defects',
            options={'ordering': ['-created_at'], 'permissions': [('can_view_department_defects', 'Может просматривать дефекты своего отдела')]},
        ),
    ]
