# Generated by Django 5.2.12 on 2026-04-28 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('defects', '0004_alter_defects_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defects',
            name='responsible_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.departments'),
        ),
    ]
